name: Ruby Spec Tests

on: [push, pull_request]

jobs:
  spec_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    - name: Install dependencies
      run: |
        gem install bundler -v 2.3.7
        bundle install --jobs 4 --retry 3

    - name: Run spec tests
      run: bundle exec rspec
